name: Deploy static content to Pages
on:
  push:
      branches: ["main"]
  workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        
        steps:
            # - name: Checkout Repository
            #   uses: actions/checkout@v4
            
            # - name: Build and Push Docker images
            #   env:
            #     DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            #     DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
            #   run: |
            #     docker build -t vera23/test-actions:latest .
            #     echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            #     docker push vera23/test-actions:latest
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v3

            # - name: Login to Docker Hub
            #   uses: docker/login-action@v3
            #   with:
            #     username: ${{ secrets.DOCKERHUB_USERNAME }}
            #     password: ${{ secrets.DOCKERHUB_TOKEN }}

            # - name: Build and push
            #   uses: docker/build-push-action@v5
            #   with:
            #     push: true
            #     tags: vera23/test-actions:latest

          - name: Copy docker-compose.yml to remote server
            run: |
              set -euo pipefail
              sudo apt update && sudo apt install -y openssh-client
              mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
              cat ~/.ssh/id_rsa
              
              ssh -oBatchMode=yes -p 22 vera@89.66.142.90 /bin/bash -s << EOT
              set -euxo pipefail
              docker stop test-actions
              sudo docker pull vera23/test-actions:latest
              sudo docker run -d --name test-actions -p 80:80 vera23/test-actions:latest
              EOT
