name: Deploy static content to Pages
on:
  push:
      branches: ["main"]
  workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Build and Push Docker image
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
              run: |
                docker build -t vera23/test-actions:latest .
                echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                docker push vera23/test-actions:latest
